# Impport Modules

In [1]:
import pandas as pd
import numpy as np

import time
import sys

from ML_toolbox import data_describe as dd

# Load Data

In [2]:
path = 'data/'
file = ['all_data']

result_path = 'result/'
result_file = ['brand','category', 'brand_category']


df_all = pd.read_csv(f'{path}{file[0]}.csv', encoding='utf8')

print(df_all.shape)
print(df_all.columns)
df_all.head(5)

(649, 21)
Index(['cart_id', 'member_id', 'retailer', 'address', 'channel', 'category',
       'brand', 'cnt', 'per_price', 'shipping_fee', 'discount', 'payment',
       'attribute', 'additional_purchase', 'age', 'regist_days',
       'last_purchaseday', 'tol_purchase_price', 'tol_purchase_time', 'gender',
       'membership_source'],
      dtype='object')

,cart_id,member_id,retailer,address,channel,category,brand,cnt,per_price,shipping_fee,...,payment,attribute,additional_purchase,age,regist_days,last_purchaseday,tol_purchase_price,tol_purchase_time,gender,membership_source
0,TG180128J00429,5105005930,family,2,Mobile,10,A,1,558,0,...,credit_card,0,0,0,282,282,558,1,-1,web
1,TG180225T00061,5503419373,7_11,11,Mobile,8,K,2,432,0,...,credit_card,0,0,0,31,-1,0,0,-1,web
2,TG180225T00061,5503419373,7_11,11,Mobile,2,K,1,288,0,...,credit_card,0,0,0,31,-1,0,0,-1,web
3,TG180308N00176,5506618770,7_11,13,Mobile,13,A,1,620,0,...,credit_card,0,0,0,31,-1,0,0,-1,web
4,TG180314X01154,5501147671,family,11,Mobile,2,K,2,288,0,...,credit_card,0,0,0,31,-1,0,0,-1,web

In [3]:
# describe data

dd.data_describe(df_all)

                     duplicate  is_null  null_number null_rate(%)
cart_id                    284    False            0         0.00
member_id                  254    False            0         0.00
retailer                     3     True           52         8.01
address                     18    False            0         0.00
channel                      4    False            0         0.00
category                    16    False            0         0.00
brand                       10    False            0         0.00
cnt                          6    False            0         0.00
per_price                   78    False            0         0.00
shipping_fee                 2    False            0         0.00
discount                     2    False            0         0.00
payment                      3    False            0         0.00
attribute                    2    False            0         0.00
additional_purchase          2    False            0         0.00
age                          7    False            0         0.00
regist_days                 20    False            0         0.00
last_purchaseday            15    False            0         0.00
tol_purchase_price          12    False            0         0.00
tol_purchase_time            4    False            0         0.00
gender                       2    False            0         0.00
membership_source            3     True           44         6.78

# Calculate Rating
## 1. Brand Rating

In [4]:
# count each member brand pair purchase times

df_brand_rating = df_all[['member_id','brand','cnt']].groupby(['member_id','brand'])['cnt'].sum()
df_brand_rating.head(10)

member_id   brand
4800838500  K         1
4801541605  K         2
4801696903  K         5
4802739705  A         1
4803019306  C         2
            K         1
            others    1
4803952302  A         1
            others    1
4804482902  A         1
Name: cnt, dtype: int64

In [5]:
df_brand_rating = df_brand_rating.reset_index(inplace=False, level=['member_id','brand'])  
print(df_brand_rating.shape)
df_brand_rating.head(10)

(476, 3)

    member_id   brand  cnt
0  4800838500       K    1
1  4801541605       K    2
2  4801696903       K    5
3  4802739705       A    1
4  4803019306       C    2
5  4803019306       K    1
6  4803019306  others    1
7  4803952302       A    1
8  4803952302  others    1
9  4804482902       A    1

## 2. Category Rating

In [6]:
# count each member category pair purchase times

df_cat_rating = df_all[['member_id','category','cnt']].groupby(['member_id','category'])['cnt'].sum()
df_cat_rating.head(10)

member_id   category
4800838500  6           1
4801541605  11          2
4801696903  6           2
            9           3
4802739705  8           1
4803019306  1           1
            3           1
            6           2
4803952302  3           1
            8           1
Name: cnt, dtype: int64

In [7]:
df_cat_rating = df_cat_rating.reset_index(inplace=False, level=['member_id','category'])  
print(df_cat_rating.shape)
df_cat_rating.head(10)

(530, 3)

    member_id  category  cnt
0  4800838500         6    1
1  4801541605        11    2
2  4801696903         6    2
3  4801696903         9    3
4  4802739705         8    1
5  4803019306         1    1
6  4803019306         3    1
7  4803019306         6    2
8  4803952302         3    1
9  4803952302         8    1

## 3. Category & Brand Rating

In [8]:
# count each member category pair purchase times

df_cb_rating = df_all[['member_id','category','brand','cnt']].groupby(['member_id','category','brand'])['cnt'].sum()
df_cb_rating.head(10)

member_id   category  brand
4800838500  6         K         1
4801541605  11        K         2
4801696903  6         K         2
            9         K         3
4802739705  8         A         1
4803019306  1         C         1
            3         others    1
            6         C         1
                      K         1
4803952302  3         others    1
Name: cnt, dtype: int64

In [9]:
df_cb_rating = df_cb_rating.reset_index(inplace=False, level=['member_id','category','brand'])  
print(df_cb_rating.shape)
df_cb_rating.head(10)

(546, 4)

    member_id  category   brand  cnt
0  4800838500         6       K    1
1  4801541605        11       K    2
2  4801696903         6       K    2
3  4801696903         9       K    3
4  4802739705         8       A    1
5  4803019306         1       C    1
6  4803019306         3  others    1
7  4803019306         6       C    1
8  4803019306         6       K    1
9  4803952302         3  others    1

In [10]:
df_cb_rating.category = df_cb_rating.category.astype(str)

df_cb_rating['item'] = df_cb_rating.category + df_cb_rating.brand

df_cb_rating = df_cb_rating.reindex(columns=['member_id', 'item','category', 'brand', 'cnt'])
df_cb_rating.head()

    member_id item category brand  cnt
0  4800838500   6K        6     K    1
1  4801541605  11K       11     K    2
2  4801696903   6K        6     K    2
3  4801696903   9K        9     K    3
4  4802739705   8A        8     A    1

In [11]:
# This table is used to record the new id's brand and category 

cat_brand_table = df_cb_rating.drop(['member_id', 'cnt'],axis=1)
cat_brand_table.drop_duplicates();
cat_brand_table.head(10)

      item category   brand
0       6K        6       K
1      11K       11       K
2       6K        6       K
3       9K        9       K
4       8A        8       A
5       1C        1       C
6  3others        3  others
7       6C        6       C
8       6K        6       K
9  3others        3  others

In [12]:
# This table is used to do recommand

df_cb_rating_new = df_cb_rating.drop(['category','brand'], axis=1)
df_cb_rating_new.head()

    member_id item  cnt
0  4800838500   6K    1
1  4801541605  11K    2
2  4801696903   6K    2
3  4801696903   9K    3
4  4802739705   8A    1

# Recomand system

In [13]:
from recommand_sys_svd import svd_recommand_sys as srs
rs = srs()

## 1. Brand

In [14]:
print(max(df_brand_rating.cnt))
df_brand_rating.cnt.unique()

10

array([ 1,  2,  5,  3,  4,  6,  8, 10,  9], dtype=int64)

In [15]:
brand_result = rs.svd_recommand(df_brand_rating,
                                 'member_id',
                                 'brand',
                                 rating_scale=(1,8),
                                 n_factors=50,
                                 test_size=.25,
                                 top_n=5)
brand_result

RMSE: 1.0138
RMSE: 1.0137925011393392

           recommand_1 recommand_2 recommand_3 recommand_4 recommand_5
5404675862           F           M           P           A           D
5007079925           M           P           L           K           A
70005484F1      others           C           L           B           F
4906721510           F           B           D           P           C
68015417D3           D           M           C           A           L
65037796A3           L           F           C           M           A
5300567655           F           D           B      others           C
5303305152           K           M           D           C           F
5305495251           M           P           C           D           K
5000580425           L           P           M           C           D
5305931751           F           C           A           K           M
5702485692           D           K           A           L           C
5305803153           L           C           F           P           K
4903980012           P           D           C           B           L
5603547385      others           P           B           F           A
5300533754           L           F           C           D           M
4901325410           K      others           A           B           P
5102929635           K           B           P           F      others
5706981391           C           A           B           F           P
5706770992           D           M           F           L           C
5006964621           P           A      others           K           L
5205852741           K           F           B           P      others
5301306653           C           D           A           L           P
66041280B0           K           L           P      others           C
5600009581           C           A           M           D           L
5507465074           P           B           D           A           F
5704243793           L           F           P           B           A
5500921374           P           B           K           A           D
67031996C0           B           F           C           P           D
65016975A2           M           L           B           C           F
...                ...         ...         ...         ...         ...
4807113801           D      others           K           M           C
5001814025           K           M           L           A           C
5604426883           F           A      others           B           D
68044297D2           D      others           M           P           L
5002178824      others           P           B           M           D
5300513750           A      others           M           D           L
68073242D5           D           P           M           F           A
5300454254           C           F           D           A           L
5003293124           D           M           L           K      others
5607084481           P           F           D      others           C
5001504725           B           L           A           C           K
67036896C0           F           B      others           A           K
5703160390           K           L           C           M           A
5106899431           K           F           D      others           B
66059996B4      others           C           K           F           M
5105005930           F           P      others           A           K
66009353B0           C           M           F           L           B
5403889165      others           A           F           B           C
5202948743      others           L           D           P           C
70025923F4           M           D           B           P           C
5600261180           K           P           B           A           L
5500055574           C           L           P           D           A
5303560750           B      others           P           K           A
68025228D1           F           L           D           C           B
4903316115           F           K           B           P           A
66055727B0           B           P           L           K           A
5005959423           L           A           C           B           F
5404719563           K           P           D           B           F
5501610271           M           L           P           F           A
5001835620           C           L           M      others           A

[218 rows x 5 columns]

In [16]:
brand_result.to_csv(f'{result_path}recommand_{result_file[0]}.csv', encoding='utf8')

## 2. Category

In [17]:
print(max(df_cat_rating.cnt))
df_cat_rating.cnt.unique()

8

array([1, 2, 3, 4, 7, 8, 5, 6], dtype=int64)

In [18]:
cat_result = rs.svd_recommand(df_cat_rating,
             'member_id',
             'category',
             rating_scale=(1,8),
             n_factors=50,
             test_size=.25,
             top_n=5)
cat_result

RMSE: 0.7182
RMSE: 0.7182262502556007

           recommand_1 recommand_2 recommand_3 recommand_4 recommand_5
6.90E+12             4           2           9          10           6
70030811F4           3           8           6           5          14
5605133984          11          16           7          15           1
690035690            4          15           7           2           3
5502455071          13           9           1           6           7
67034684C0          16          14          13           9           7
5002178824           1          10          13           4          15
65037796A3           6           2          13           3          14
5407219565          12           9           3           5          15
5704685494           2          16          11           5           8
68008623D3           3           4          11          15          10
5305931751           2           8          13          16           6
5300912555           9           2           1           3           5
5301614153          16          10          11          12          13
67006674C5          15           5           2          14           4
5401745665           5          12          15           4           3
5603832880           3           6           8           7           2
4906819116          13          11           9           8           6
5300533754           2          13          12          14           7
6907162800           4           1          14           7          11
4906721510           6          10          13          12           4
4906977515           5          10          12          13          16
70062102F2          12          13           4           3          10
4802739705          11           5          13          16           2
5100922032           8           2           1           5          14
70001425F2           2          11           8           3          10
5604426883           7          11           8           9           4
70016745F2           5          10           4           2          15
5402119462           1          14           8          15           7
4903980012          13           9           2           5          10
...                ...         ...         ...         ...         ...
5303225353          14           6          12           3          16
5207127940          15          12           4           5           3
65044293A4          16           5          13           9           1
68073242D5           8          14          13           1           3
5000580425          16          12           2           4           9
4804482902           2           3           6          14           8
66009353B0           9           2           8           6          15
67068671C4          11           7           2           6           4
5700430994          10          12           1           4          13
5305367252           7           2          14           8           4
5202020745           8           6           2          11          14
5103038833           4           7           2           5          13
66041280B0          13           4          15           5          16
5105005930           2          14           8          13          15
5702485692           2           8           1          11           7
5506618770          14           9           4           8           2
67021096C4           1          11          15           2           3
70071215F3           8          11           1          16          14
4801696903          12           7           6          15           9
5601777584          13          12           6           8          14
5401928462           7           5           1          11           4
5705683393           3           1           2          15          16
5602343884           3           6           5           2          10
66059996B4           6          12          16          13          10
4806356300           9           2           5           1          16
65026961A1           7           5          16          12          15
5102098630          13           6           9          10          11
4803952302          13          16          14           2           8
5001814025           5           8          15          11           1
5702904694           5           2           4           8          10

[228 rows x 5 columns]

In [19]:
# transform category id to name 

cat_map = {1:'去角質', 2:'沐浴', 3:'其他', 4:'卸妝', 5:'底妝',
           6:'保濕', 7:'持妝', 8:'洗髮', 9:'洗顏', 10:'眉毛',
           11:'美白', 12:'眼線', 13:'睫毛', 14:'補妝', 15:'遮瑕', 16:'護唇'}

for i in range(cat_result.shape[1]):
    cat_result['recommand_{}'.format(i+1)] = cat_result['recommand_{}'.format(i+1)].astype(int)
    cat_result['recommand_{}'.format(i+1)] = cat_result.loc[:,'recommand_{}'.format(i+1)].map(cat_map)
cat_result

           recommand_1 recommand_2 recommand_3 recommand_4 recommand_5
6.90E+12            卸妝          沐浴          洗顏          眉毛          保濕
70030811F4          其他          洗髮          保濕          底妝          補妝
5605133984          美白          護唇          持妝          遮瑕         去角質
690035690           卸妝          遮瑕          持妝          沐浴          其他
5502455071          睫毛          洗顏         去角質          保濕          持妝
67034684C0          護唇          補妝          睫毛          洗顏          持妝
5002178824         去角質          眉毛          睫毛          卸妝          遮瑕
65037796A3          保濕          沐浴          睫毛          其他          補妝
5407219565          眼線          洗顏          其他          底妝          遮瑕
5704685494          沐浴          護唇          美白          底妝          洗髮
68008623D3          其他          卸妝          美白          遮瑕          眉毛
5305931751          沐浴          洗髮          睫毛          護唇          保濕
5300912555          洗顏          沐浴         去角質          其他          底妝
5301614153          護唇          眉毛          美白          眼線          睫毛
67006674C5          遮瑕          底妝          沐浴          補妝          卸妝
5401745665          底妝          眼線          遮瑕          卸妝          其他
5603832880          其他          保濕          洗髮          持妝          沐浴
4906819116          睫毛          美白          洗顏          洗髮          保濕
5300533754          沐浴          睫毛          眼線          補妝          持妝
6907162800          卸妝         去角質          補妝          持妝          美白
4906721510          保濕          眉毛          睫毛          眼線          卸妝
4906977515          底妝          眉毛          眼線          睫毛          護唇
70062102F2          眼線          睫毛          卸妝          其他          眉毛
4802739705          美白          底妝          睫毛          護唇          沐浴
5100922032          洗髮          沐浴         去角質          底妝          補妝
70001425F2          沐浴          美白          洗髮          其他          眉毛
5604426883          持妝          美白          洗髮          洗顏          卸妝
70016745F2          底妝          眉毛          卸妝          沐浴          遮瑕
5402119462         去角質          補妝          洗髮          遮瑕          持妝
4903980012          睫毛          洗顏          沐浴          底妝          眉毛
...                ...         ...         ...         ...         ...
5303225353          補妝          保濕          眼線          其他          護唇
5207127940          遮瑕          眼線          卸妝          底妝          其他
65044293A4          護唇          底妝          睫毛          洗顏         去角質
68073242D5          洗髮          補妝          睫毛         去角質          其他
5000580425          護唇          眼線          沐浴          卸妝          洗顏
4804482902          沐浴          其他          保濕          補妝          洗髮
66009353B0          洗顏          沐浴          洗髮          保濕          遮瑕
67068671C4          美白          持妝          沐浴          保濕          卸妝
5700430994          眉毛          眼線         去角質          卸妝          睫毛
5305367252          持妝          沐浴          補妝          洗髮          卸妝
5202020745          洗髮          保濕          沐浴          美白          補妝
5103038833          卸妝          持妝          沐浴          底妝          睫毛
66041280B0          睫毛          卸妝          遮瑕          底妝          護唇
5105005930          沐浴          補妝          洗髮          睫毛          遮瑕
5702485692          沐浴          洗髮         去角質          美白          持妝
5506618770          補妝          洗顏          卸妝          洗髮          沐浴
67021096C4         去角質          美白          遮瑕          沐浴          其他
70071215F3          洗髮          美白         去角質          護唇          補妝
4801696903          眼線          持妝          保濕          遮瑕          洗顏
5601777584          睫毛          眼線          保濕          洗髮          補妝
5401928462          持妝          底妝         去角質          美白          卸妝
5705683393          其他         去角質          沐浴          遮瑕          護唇
5602343884          其他          保濕          底妝          沐浴          眉毛
66059996B4          保濕          眼線          護唇          睫毛          眉毛
4806356300          洗顏          沐浴          底妝         去角質          護唇
65026961A1          持妝          底妝          護唇          眼線          遮瑕
5102098630          睫毛          保濕          洗顏          眉毛          美白
4803952302          睫毛          護唇          補妝          沐浴          洗髮
5001814025          底妝          洗髮          遮瑕          美白         去角質
5702904694          底妝          沐浴          卸妝          洗髮          眉毛

[228 rows x 5 columns]

In [20]:
cat_result.to_csv(f'{result_path}recommand_{result_file[1]}.csv', encoding='utf8')

## 3. Category & Brand

In [21]:
print(max(df_cb_rating_new.cnt))
df_cb_rating_new.cnt.unique()

8

array([1, 2, 3, 4, 6, 8, 5], dtype=int64)

In [22]:
cb_result = rs.svd_recommand(df_cb_rating_new,
             'member_id',
             'item',
             rating_scale=(1,8),
             n_factors=50,
             test_size=.25,
             top_n=5)
cb_result

RMSE: 0.5151
RMSE: 0.5151262084636336

           recommand_1 recommand_2 recommand_3 recommand_4 recommand_5
5603547385         15B         16B          9K         12F         13P
4803952302         15D          6C     5others         12F          3B
5006919923          8A          7B         13M         12F     3others
5000968424          6K         13M          2K         13P          3B
65026961A1         16K    13others         13A          7K          5B
5104564930         13M          9K          6K          6C    13others
70002714F0         15D         13F         13P         16K    12others
5400647764         11K         13M         15D    12others         16B
68042825D0         13M         13F          4B         15D         12F
6.90E+12      13others          5B         15D          6A         11K
5002178824          3L          7K         13P         11K         13D
5101285732         15D         13M          4B          2K          7K
5001504725         13M          6K          9K         15B          3B
70013714F1         13P          3B     5others    12others          9K
5401745665         13M          6C          4K          5B          6K
5207033541    13others         12F         14B         13D          6C
67034684C0         16K         13F          3B          8K         13P
67057834C4          6A         16K          9K         13M         16B
5202948743          8K         14B         10B          3L         16B
5704243793         15D         16B         13M          4K         11K
66041280B0         16B          6B          6A          3B          7B
4804482902         11K     3others         12F         13F          3B
5000449324         14B          8A          6B          8K    13others
5105843532         13M         13F          4B          6C     3others
65028154A3          3L         10B          1C          7K          8K
5704062295         13P         15B          1C         11K          7K
66039125B3         13F          7B          3B         10B          4K
66009353B0         10B         11K         13P          4K         13F
5301665553         11K         10A          9K          6B          6A
5003293124          6B         16K     3others         13D          7K
...                ...         ...         ...         ...         ...
5307385454          2K         16K          6A         13P          6C
5103038833         13P         15D         10B          6C          4B
5603832880         13F          6K         13D          8K     3others
5102085634         13D          1C    13others         11K     3others
70005484F1          2K          8K         13P          7K          3L
68025228D1          6A     3others         13P    13others          9K
5300165354         11K         13P    12others          5B          4K
5502455071         15D         13A         10B         16K         14B
66059996B4          6C     5others         14B         15B          8K
5403764162         13M         15D          4K          4B         16B
5201865945         12F          6K         13M         16K          6B
4901325410         14B          4B         13F          4K         12F
690701230           6B          3B          8K         11K     5others
5303225353          1C         13D          5B          3B          7B
5501147671          9K     3others    12others         13M          2K
5506618770         13M          5B         16B          8A    13others
5005959423         16K    13others          2K          8K     5others
5200167545          7K         16K         13A          8K         10B
5102126932         16B          6K          1C          6B          6A
67014735C3          2K          6A          9K          6K          4B
5001814025         13M         15D          9K    12others          7B
70071215F3          5B         13A          4B         15D          3B
5507324570         10B          8K         13F     3others          6B
5200810141         13M          5B          7B         13P     5others
67002815C2          7K         13F         15D         13P          6K
5201112542          9K         13P    13others         13M    12others
5203351942         13M          8K    12others         16B         14B
4902511012          3B          6C         15D          1C          5B
5500190271          2K         10A         13D          6K     5others
5306760652         10A          4B          3B         15D         10B

[235 rows x 5 columns]

In [23]:
# transform category id to name 

def transform_cb(A):
    cat_map = {1:'去角質', 2:'沐浴', 3:'其他', 4:'卸妝', 5:'底妝',
           6:'保濕', 7:'持妝', 8:'洗髮', 9:'洗顏', 10:'眉毛',
           11:'美白', 12:'眼線', 13:'睫毛', 14:'補妝', 15:'遮瑕', 16:'護唇'}
    return (cat_map[int(cat_brand_table[cat_brand_table.item==A]['category'].values[0])], cat_brand_table[cat_brand_table.item==A].loc[:,'brand'].values[0])


for i in range(cb_result.shape[1]):
    for j in range(cb_result.shape[0]):
        A = cb_result.ix[j][i]
        cb_result.ix[j][i] = transform_cb(A)
        
cb_result

C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if sys.path[0] == '':
C:\Users\ASUS\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:13: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  del sys.path[0]

,recommand_1,recommand_2,recommand_3,recommand_4,recommand_5
5603547385,"(遮瑕, B)","(護唇, B)","(洗顏, K)","(眼線, F)","(睫毛, P)"
4803952302,"(遮瑕, D)","(保濕, C)","(底妝, others)","(眼線, F)","(其他, B)"
5006919923,"(洗髮, A)","(持妝, B)","(睫毛, M)","(眼線, F)","(其他, others)"
5000968424,"(保濕, K)","(睫毛, M)","(沐浴, K)","(睫毛, P)","(其他, B)"
65026961A1,"(護唇, K)","(睫毛, others)","(睫毛, A)","(持妝, K)","(底妝, B)"
5104564930,"(睫毛, M)","(洗顏, K)","(保濕, K)","(保濕, C)","(睫毛, others)"
70002714F0,"(遮瑕, D)","(睫毛, F)","(睫毛, P)","(護唇, K)","(眼線, others)"
5400647764,"(美白, K)","(睫毛, M)","(遮瑕, D)","(眼線, others)","(護唇, B)"
68042825D0,"(睫毛, M)","(睫毛, F)","(卸妝, B)","(遮瑕, D)","(眼線, F)"
6.90E+12,"(睫毛, others)","(底妝, B)","(遮瑕, D)","(保濕, A)","(美白, K)"
5002178824,"(其他, L)","(持妝, K)","(睫毛, P)","(美白, K)","(睫毛, D)"
5101285732,"(遮瑕, D)","(睫毛, M)","(卸妝, B)","(沐浴, K)","(持妝, K)"
5001504725,"(睫毛, M)","(保濕, K)","(洗顏, K)","(遮瑕, B)","(其他, B)"
70013714F1,"(睫毛, P)","(其他, B)","(底妝, others)","(眼線, others)","(洗顏, K)"
5401745665,"(睫毛, M)","(保濕, C)","(卸妝, K)","(底妝, B)","(保濕, K)"
5207033541,"(睫毛, others)","(眼線, F)","(補妝, B)","(睫毛, D)","(保濕, C)"
67034684C0,"(護唇, K)","(睫毛, F)","(其他, B)","(洗髮, K)","(睫毛, P)"
67057834C4,"(保濕, A)","(護唇, K)","(洗顏, K)","(睫毛, M)","(護唇, B)"
5202948743,"(洗髮, K)","(補妝, B)","(眉毛, B)","(其他, L)","(護唇, B)"
5704243793,"(遮瑕, D)","(護唇, B)","(睫毛, M)","(卸妝, K)","(美白, K)"
66041280B0,"(護唇, B)","(保濕, B)","(保濕, A)","(其他, B)","(持妝, B)"
4804482902,"(美白, K)","(其他, others)","(眼線, F)","(睫毛, F)","(其他, B)"
5000449324,"(補妝, B)","(洗髮, A)","(保濕, B)","(洗髮, K)","(睫毛, others)"
5105843532,"(睫毛, M)","(睫毛, F)","(卸妝, B)","(保濕, C)","(其他, others)"
65028154A3,"(其他, L)","(眉毛, B)","(去角質, C)","(持妝, K)","(洗髮, K)"
5704062295,"(睫毛, P)","(遮瑕, B)","(去角質, C)","(美白, K)","(持妝, K)"
66039125B3,"(睫毛, F)","(持妝, B)","(其他, B)","(眉毛, B)","(卸妝, K)"
66009353B0,"(眉毛, B)","(美白, K)","(睫毛, P)","(卸妝, K)","(睫毛, F)"
5301665553,"(美白, K)","(眉毛, A)","(洗顏, K)","(保濕, B)","(保濕, A)"
5003293124,"(保濕, B)","(護唇, K)","(其他, others)","(睫毛, D)","(持妝, K)"
...,...,...,...,...,...
5307385454,"(沐浴, K)","(護唇, K)","(保濕, A)","(睫毛, P)","(保濕, C)"
5103038833,"(睫毛, P)","(遮瑕, D)","(眉毛, B)","(保濕, C)","(卸妝, B)"
5603832880,"(睫毛, F)","(保濕, K)","(睫毛, D)","(洗髮, K)","(其他, others)"
5102085634,"(睫毛, D)","(去角質, C)","(睫毛, others)","(美白, K)","(其他, others)"
70005484F1,"(沐浴, K)","(洗髮, K)","(睫毛, P)","(持妝, K)","(其他, L)"
68025228D1,"(保濕, A)","(其他, others)","(睫毛, P)","(睫毛, others)","(洗顏, K)"
5300165354,"(美白, K)","(睫毛, P)","(眼線, others)","(底妝, B)","(卸妝, K)"
5502455071,"(遮瑕, D)","(睫毛, A)","(眉毛, B)","(護唇, K)","(補妝, B)"
66059996B4,"(保濕, C)","(底妝, others)","(補妝, B)","(遮瑕, B)","(洗髮, K)"
5403764162,"(睫毛, M)","(遮瑕, D)","(卸妝, K)","(卸妝, B)","(護唇, B)"
5201865945,"(眼線, F)","(保濕, K)","(睫毛, M)","(護唇, K)","(保濕, B)"
4901325410,"(補妝, B)","(卸妝, B)","(睫毛, F)","(卸妝, K)","(眼線, F)"
690701230,"(保濕, B)","(其他, B)","(洗髮, K)","(美白, K)","(底妝, others)"
5303225353,"(去角質, C)","(睫毛, D)","(底妝, B)","(其他, B)","(持妝, B)"
5501147671,"(洗顏, K)","(其他, others)","(眼線, others)","(睫毛, M)","(沐浴, K)"
5506618770,"(睫毛, M)","(底妝, B)","(護唇, B)","(洗髮, A)","(睫毛, others)"
5005959423,"(護唇, K)","(睫毛, others)","(沐浴, K)","(洗髮, K)","(底妝, others)"
5200167545,"(持妝, K)","(護唇, K)","(睫毛, A)","(洗髮, K)","(眉毛, B)"
5102126932,"(護唇, B)","(保濕, K)","(去角質, C)","(保濕, B)","(保濕, A)"
67014735C3,"(沐浴, K)","(保濕, A)","(洗顏, K)","(保濕, K)","(卸妝, B)"
5001814025,"(睫毛, M)","(遮瑕, D)","(洗顏, K)","(眼線, others)","(持妝, B)"
70071215F3,"(底妝, B)","(睫毛, A)","(卸妝, B)","(遮瑕, D)","(其他, B)"
5507324570,"(眉毛, B)","(洗髮, K)","(睫毛, F)","(其他, others)","(保濕, B)"
5200810141,"(睫毛, M)","(底妝, B)","(持妝, B)","(睫毛, P)","(底妝, others)"
67002815C2,"(持妝, K)","(睫毛, F)","(遮瑕, D)","(睫毛, P)","(保濕, K)"
5201112542,"(洗顏, K)","(睫毛, P)","(睫毛, others)","(睫毛, M)","(眼線, others)"
5203351942,"(睫毛, M)","(洗髮, K)","(眼線, others)","(護唇, B)","(補妝, B)"
4902511012,"(其他, B)","(保濕, C)","(遮瑕, D)","(去角質, C)","(底妝, B)"
5500190271,"(沐浴, K)","(眉毛, A)","(睫毛, D)","(保濕, K)","(底妝, others)"
5306760652,"(眉毛, A)","(卸妝, B)","(其他, B)","(遮瑕, D)","(眉毛, B)"

In [24]:
cb_result.to_csv(f'{result_path}recommand_{result_file[2]}.csv', encoding='utf8')